version: "4.31.1"
services:
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SPRING_SERVER_URL=http://server:9090
  server:
    build: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
  db:
    image: postgres:latest
    ports:
      - "2345:5432"
    volumes:
      - /var/lib/postresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345